## ibkc olvz voed qzxg
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: always
    depends_on:
      - postgres
      - postfix
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html/vendor
      - ./.env:/var/www/html/.env

    environment:
      APP_ENV: production
      APP_KEY: base64:ibkc olvz voed qzxg
      APP_DEBUG: true
      DB_HOST: postgres
      DB_DATABASE: db-tourneyhub
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      MAIL_MAILER: smtp
      MAIL_HOST: postfix
      MAIL_PORT: 587
      MAIL_USERNAME: villarrealperezjesusalberto@gmail.com
      MAIL_PASSWORD: ibkc olvz voed qzxg
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: villarrealperezjesusalberto@gmail.com
      MAIL_FROM_NAME: "TourneyHub"

  postgres:
    image: postgres:latest
    container_name: postgres-users
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db-tourneyhub
    volumes:
      - postgres_data:/var/lib/postgresql/data

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certs:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email villarrealperezjesusalberto@gmail.com --agree-tos --no-eff-email -d mishistema.servecounterstrike.com

  postfix:
    build:
      context: ./docker/postfix
      dockerfile: Dockerfile
    container_name: postfix
    restart: always
    environment:
      RELAY_HOST: smtp.gmail.com
      RELAY_PORT: 587
      SMTP_USER: villarrealperezjesusalberto@gmail.com
      SMTP_PASS: ibkc olvz voed qzxg

volumes:
  postgres_data:
