services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db-users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
